name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |

        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin login"
        echo "_________________ New version: $NEW_VERSION!!"
        
    - name: Git Semantic Version
      id: version
      uses: PaulHatch/semantic-version@v5.4.0
      with:
        major_pattern: "mayor" 
        minor_pattern: "feat" 
        format: "${major}.${minor}.${patch}"

    # - name: Build docker image
    #   run: |
    #     docker build -t minichii/docker-graphql:0.0.1 .
    #     docker build -t minichii/docker-graphql:latest .
        
    # - name: Push docker image
    #   run: |
    #     docker push minichii/docker-graphql:0.0.1
    #     docker push minichii/docker-graphql:latest
    

        
    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
